version: "3.7"
services:
  url-collector:
    build:
      context: .
    ports:
      - "8080:8080"
    links:
      - "database"
    volumes:
      - ".:/code"
    command: "sh -c 'diesel database setup && cargo run'"
    working_dir: "/code"
      
      
  database:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: "alohomora"
    ports:
      - "5432:5432"
